name: Birthday Checker

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8 AM UTC daily
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  check-birthdays:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit
        pip install supabase
        pip install pandas
        # Add any other required packages
    
    - name: Run birthday checker
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
      run: python birthday_checker.py 