[server]
runOnSave = true
maxUploadSize = 200
maxMessageSize = 200

[client]
showErrorDetails = false

[runner]
fastReruns = true

[theme]
primaryColor = "#1e1b4b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif" 