# Supabase credentials
SUPABASE_URL = "https://snozffkrnbaxfsudhaob.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNub3pmZmtybmJheGZzdWRoYW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NTkyMzYsImV4cCI6MjA1NzEzNTIzNn0.Pa_1xok3tW-qoIlkZa2VCZrizCMjsSw9OCFFWvcFZr0"

# Email configuration
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 465
sender_email = "ebukweku@gmail.com"  
sender_password = "xhpz irms lmbh kbzd"   
# admin_emails = "admin1@email.com,admin2@email.com"  
